wfxr/forgit

README.md, forgit.plugin.zsh
This doesn't change the normal behaviour of the plugin at all.
It simply allows the user to override the default aliases with something else via environment variables.
=> Allow custom aliases

forgit.plugin.sh, forgit.plugin.zsh
The gitignore templates used here is from [dvcs/gitignore](https://github.com/dvcs/gitignore), which is
the same one used by [gitignore.io](https://www.gitignore.io/).
Environment variable `FORGIT_GI_USE_LOCAL` is used as a switch to
enable this feature, otherwise the original method is used by default.
`forgit::ignore::update` and `forgit::ignore::get` are rewritten
to download the repo, to get templates from the local repo.
Local variable `preview` in `forgit:ignore` is also rewritten to
get the preview from there.
All these implementations are put into an `if` conditional statement.
If you wanna accept this feature, you'd better reindent the files after merge.
Not only because I didn't indent the content for a better diff view
on purpose, but also the indentations in …
=> Feature: use gitignore templates from local repo directly

README.md, forgit.plugin.zsh
May fix #21 as well.
I noticed this was especially needed in `forgit::add` because it's default preview command shows nothing for completely untracked files.
=> Enable configuring preview command for every cmd

README.md, forgit.plugin.zsh
I added `grh` (git reset HEAD) command to unstage the staged files. This is the opposite of `git add`.
Could you please review and add screenshot to README?
Hope you find this PR useful 🙂
=> Add `grh` command for `git reset HEAD` (unstage)

forgit.plugin.zsh
I wasn't sure whether this was intended or not, but I noticed that reset files are printed out twice: once by `git reset HEAD` and once by `git status` afterwards. I know that they are not printing exactly the same information, but to me, the first output is not really necessary. If you agree, feel free to merge.
=> Added -q flag for git reset HEAD

forgit.plugin.fish
I noticed that the fish commands were not working on multi-select (using ctrl+r). 
Steps to repro:
1. Source fish version
2. modify multiple files
3. `ga`
4. ctrl+r
5. enter
Expected:
All files modified are add
Observed:
Crash :( 
This seems to have to do with the way fish arrays are stored. This seems to have fixed it!
* OS: Mac OSX Mojave
@cjappl @wfxr
=> Fixed issue with mutliple inputs to git commands using ctrl+r

.github/ISSUE_TEMPLATE/bug_report.md, forgit.plugin.fish
Moving to the builtin function type -q for checking if a program exists for fish 
Fixes # (issue)
#54 
* OS: Mac OSX Mojave
@cjappl @wfxr
=> Moved from hash to type -q

forgit.plugin.fish, forgit.plugin.zsh
I had issues installing forgit and ran into the warning message that has a typo. "reqiured" instead of "required". I then fixed it for you in the zsh and fish files. (spelled correctly in the sh file)
- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] zsh 
- [ x] fish 
- [ x] zsh 
* OS: 
```
Operating System: elementary OS 5.0 Juno
Kernel: Linux 4.15.0-70-generic
Architecture: x86-64
```
- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
@cjappl @wfxr
=> :bug: fix typo in warning message

forgit.plugin.zsh
Fix some path related bugs. Add status indicator to `forgit::diff` command BTW.
* OS: Arch Linux x86_64
#39 : This pr will remove the dependency on `realpath`.
Please help sync the fish version. @cjappl
=> Fix path related bugs.

forgit.plugin.zsh
Fix more whitespace related bugs. 
#58 #62 
Steps to reproduce:
```bash
cd forgit
touch '       a  b  c  '
ga
touch '   b  c   d  '
gclean
```
- Shell
- OS
=> Fix more whitespace related bugs

forgit.plugin.fish, forgit.plugin.zsh
Add case where "ga" command can accept files as arguments
that will be passed directly to "git add" bypassing fzf.
- Shell
- OS
=> Add files as arguments

forgit.plugin.zsh
- Shell
- OS
This is [my issue](https://github.com/wfxr/forgit/issues/76) solution.
I was constantly getting error from bat: `no such file: [M] file-name`, but I was using diff-so-fancy as pager.
The thing was in fzf environment variable (fzf latest version 0.20.0), and it is even mentioned in [fzf's README](https://github.com/junegunn/fzf#preview-window): "Since fzf is a general-purpose text filter rather than a file finder, it is not a good idea to add `--preview` option to your `$FZF_DEFAULT_OPTS`"
=> fzf preview bug fixed

forgit.plugin.fish
There was an error in the git stash viewer for fish, the parenthesis should not be escaped. This pr fixes the error.
- Shell
- OS
=> Fix syntax error in git stash viewer for fish

README.md
The bug in 3.1 was solved by https://github.com/fish-shell/fish-shell/issues/6955
Resolves #87
- [ x] I have performed a self-review of my code
- [ x] I have commented my code in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [ x] Documentation change
- Shell
- OS
=> The bug in fish <3.1 is resolved

README.md, forgit.plugin.fish, forgit.plugin.zsh
I have a use case where I need to override the pager config, so I thought I'd write a PR on the case.
My use case is that I'm using WSL 2 where they still have super slow file access across the distros. To conquer that I'm using a small script in my WSL instead of git that goes something like this:
```bash
#! /bin/bash
LINUX_GIT='/usr/bin/git'
WINDOWS_GIT='git.exe'
WORKING_DIR="$(pwd)"
if [[ "${WORKING_DIR:0:3}" == '/c/' ]]; then
$WINDOWS_GIT "$@"
else
$LINUX_GIT "$@"
fi
```
Using the interopability to my advantage to use either git inside my WSL or inside my Windows host machine depending on which repo I'm working on. Making it blazing fast in comparison to only using the WSL git.
Problem then arises with the pager. Since it's pointing to my `git.exe` when targeting repos on my Windows …
=> Configurable pager

forgit.plugin.zsh
Without the parameters some file will not be cleaned
- Shell
- OS
=> Add missing parameters to fix gclean

forgit.plugin.fish
when using forgit for the first time, the .forgit folder is not
created. forgit::ignore::update, which git glone the repo, was executed
only if the folder existed, so now it execute only if the .forgit don't
exist.
also, there some weird things in the logic with forgit::ignore::update,
some part of the code it not running in any case, since the if test -d
in the fonction is called in a fonction which is called only if the
folder don't exist, or i miss something ?
- Shell
- OS
=> fixed fish if .forgit wasn't already existing

forgit.plugin.fish, forgit.plugin.zsh
if FORGIT_GI_REPO_LOCAL is not already declared, use XDG_CACHE_HOME/.forgit/gi/repos/dvcs/gitignore if declared, and if not declared too, use the the fallback path which is ~/.forgit/gi/repos/dvcs/gitignore
- Shell
- OS
=> FORGIT_GI_REPO_LOCAL and XDG

README.md, forgit.plugin.fish, forgit.plugin.zsh
- [] I have commented my code in hard-to-understand areas
before the default option for bat where just `--color=always`, but now if FORGIT_BAT_OPTION is set it will use add the value of the variable to bat command.
for me, I want to use the following option to bat : `-pp --color=always --theme "Monokai Extended Origin"`
which I can use by setting the following in my zshrc : 
`export FORGIT_BAT_OPTION='-pp --color=always --theme="Monokai Extended Origin"'`
- Shell
- OS
=> FORGIT_BAT_OPTS to add options to bat

conf.d/forgit.plugin.fish
This pull request aims to fix a bug I had with fish and using forgit::diff
$cmd was not defined at the time opts get defined resulting in the following error : 
```
fish: Expected a command, but instead found a pipe
|env LESS='-R' less
^
```
The fix is just about moving cmd definition before opts and after repo.
I'm using the fix and seems fine.
- Shell
- OS
=> Fix forgit::diff's fzf execute because of undefined $cmd

README.md, forgit.plugin.zsh
I added `gcb` which is used to list all the branches and checkout into
one of your choice. I believe this is a useful functionality especially
when a repo has too many branches to rememmber and lookup.
The preview contains the log tree from the selected branch.
I have removed keybinding for copy commit hash on gcb alias
Signed-off-by: b10n1k <jbonatakis@gmail.com>
#26
#101
- Shell
- OS
=> Implement git-checkout to switch branches in a repo

forgit.plugin.zsh
For some reasons vim and xargs do not work well together (nvim does not have the problem).
So I rewrite the related code in a little more verbose way to improve compatibility for vim (and maybe some other terminal editors).
Related issue: #138 
- Shell
- OS
=> fix: improve compatibility for vim

conf.d/forgit.plugin.fish, forgit.plugin.zsh
Fixing #140 #139 for vim
@wfxr Please review the change I made to zsh. It appears that if we are going to return if we get arguments to gcb we should remove it from that call later in the function
- Shell
- OS
=> Fish vim gcb

README.md, forgit.plugin.zsh
Signed-off-by: Ariel Davidov <arik.davidov@gmail.com>
A combination of fixup and autosquash is useful to fix any past commit.
However, using it manually is inconvenient (see: https://fle.github.io/git-tip-keep-your-branch-clean-with-fixup-and-autosquash.html).
Fixing the last commit is easy: `git commit --amend --no-edit`.
The new function makes fixing any commit as convenient as fixing the last commit.
- Shell
- OS
=> Add fixup function

README.md, forgit.plugin.zsh
- Add `gco` to checkout a commit.
- Minor refactors to unify `forgit::checkout::file`, `forgit::checkout::branch` and `forgit::checkout::commit`.
- Shell
- OS
=> feat: add gco to checkout a commit

conf.d/forgit.plugin.fish
- [] I have commented my code in hard-to-understand areas
- [] I have made corresponding changes to the documentation
fish does not use $1 and $2 for arguments, instead it using $argv which is a array/list and to index $1, $argv[1] should be used.
I am not sure why this issue was not reported before. But I believe it has been there for a long time.
To test:
`gd branch_name `
It should works for both zsh and fish. But it only works for zsh ATM. Run command in fish, an error will be shown
- Shell
- OS
=> Bugfix: gd(git diff) for fish does not work with arguments

conf.d/forgit.plugin.fish
When defining a custom alias for the `gcb` (Git checkout branch) in alias, the custom alias is not registered; rather, `fish` will omit the following warning on start: `alias: Body cannot be empty`.
I think this is caused due to a typo between the variable that’s being tested for presence and the variable that’s later used for setting the alias.
- Shell
- OS
=> Fix `gcb` alias in Fish

README.md, forgit.plugin.zsh
I've added `gct` which is very similar to `gcb`, except that it operates on tags instead of branches. The sorting of tags treats names as versions.
- Shell
- OS
=> Implemented git checkout tag

forgit.plugin.zsh
`FORGIT_GLO_FORMAT` appears in the documentation, but it was not anywhere to be found on the code itself.
This PR just adds this missing feature.
Now, before anyone mentions `FORGIT_LOG_FORMAT` - this global variable needs to be set **before** forgit is first loaded and cannot be changed during an active session. For me it means to put it in `~/.zshenv` which gets loaded before anything else, and I consider this to be less than ideal.
- Shell
- x] zsh
- OS
=> Add missing support for `FORGIT_GLO_FORMAT`

forgit.plugin.zsh
- [n/a] I have commented my code in hard-to-understand areas
- [n/a] I have made corresponding changes to the documentation
Fix two bugs in `forgit::diff`:
- #187
- #188
- Shell
- OS
=> Improve forgit diff

README.md, forgit.plugin.zsh
Added an interactive git revert commit selector.  Works like `glo`, except that it allows to select multiple commits to be reverted.
- Shell
- OS
=> Implemented git revert commit

forgit.plugin.zsh
- [n/a] I have commented my code in hard-to-understand areas
- [n/a] I have made corresponding changes to the documentation
Arguments to fzf are passed via the `FZF_DEFAULT_OPTS` environment
variable, which can be overridden by a dedicated `FORGIT_<cmd>_FZF_OPTS`
variable for each command separately. The `--preview` argument, however,
was excluded from this mechanism and hard-coded to the fzf call, so that
there was no chance overriding it.
This patch moves the passing of this argument to the `FZF_DEFAULT_OPTS`
variable for all commands, so that it can be overridden as well.
Fixes #185
- Shell
- OS
=> Make fzf '--preview' argument overridable in environment

forgit.plugin.zsh
Before this commit, the regex for extracting the commit hash when using `grc` assumed that each line starts with '* '. This is not the case when your commit history contains merges that were not squashed and looks more like this 
```
*   7bf6560 Merge branch 'test-branch' 4 days ago
|\  
| * c753f1c (test-branch) Test commit 5 4 days ago
| * d3c7c6d Test commit 4 4 days ago
* | 1869317 Test commit 6 4 days ago
|/  
* b344261 Test commit 3 3 weeks ago
```
In the example above, selecting the line `| * c753f1c (test-branch) Test commit 5 4 days ago` would fail to revert the commit. This is now fixed.
Note: The fish implementation does not seem to have this issue.
- Shell
- OS
=> Fixed: grc fails when commit is preceded by anything else than '* '

conf.d/forgit.plugin.fish
- Shell
- OS
https://github.com/wfxr/forgit/commit/d0b3cfca33348f51a6494e5bb0c9c01934bc29bc broke `grb` i.e. `forgot::rebase` in fish.
=> fix: `forgit::rebase` not working in fish

conf.d/forgit.plugin.fish, forgit.plugin.zsh
This PR fixes a couple of issues in checkout::branch (the gcb function) related to the verbosity of the output and the ordering of the branches.
Fixes #167 
Fixes #180 
Fixes #195 
Instead of the HEAD, a wrong branch (main in the screenshot) is used as a header line (this behavior depends on the locales configuration, `LC_COLLATE="es_ES.UTF-8"` in this example). Furthermore, the list contains the last commit hash and subject, complicating the selection of the right one with fzf:
The right line is used as a header (the current HEAD, which starts with an asterisk), and the list shows just the branch names:
- Shell
- OS
=> Fix gcb problems with verbosity and collation

conf.d/forgit.plugin.fish, forgit.plugin.zsh
~- [ ] I have performed a self-review of my code~
~- [ ] I have commented my code in hard-to-understand areas~
~- [ ] I have made corresponding changes to the documentation~
https://github.com/wfxr/forgit/commit/5093c185329488448aa6e631d3e751a402729a15 broke `forgit::diff` / `gd` if the path to the repo contains spaces. This fixes the issue by wrapping the repo path in quotes.
- Shell
- OS
=> fix: `forgit::diff` not working if repo path contains spaces

README.md, conf.d/forgit.plugin.fish, forgit.plugin.zsh
Added `gbd` in fish. 
I often find that I end up with a bunch of stale branches, and I end up deleting them by hand. 
This allows for a nice way to easily delete my old branches, in a `forgit` complient way.
**NEEDS DUPLICATION IN BASH BY @wfxr or others :) **
- Shell
- OS
=> Adding support for git branch delete method in fish

forgit.plugin.zsh
=> fix: gd show empty preview when path has spaces

README.md, conf.d/forgit.plugin.fish, forgit.plugin.zsh
This PR improves `gcp` (cherry-pick) with the following features:
1. **Add FORGIT_CHERRY_PICK_FZF_OPTS**
The `gcp` command was the only command which did not have a variable to set command-specific `fzf` options. Add the according variable to source code and documentation.
2. **Preserve commit order on cherry pick**
When using a `fzf` find string which maches multiple lines, the commits could appear in a wrong order. Add `--tiebreak=index` to ensure that the correct commit order is preserved.
3. **Preserve +/- information on cherry pick**
The output of `git cherry` which is used to build the `fzf` input list for `forgit::cherry::pick` usually prefixes every line with a '-' for commits that have an equivalent in the target branch, and a '+' for commits that do not.
Previously forgit …
=> Improve cherry-pick

conf.d/forgit.plugin.fish, forgit.plugin.zsh
The preview on cherry pick was accidentally broken since we included the
+/- information in the commit list. Fix this by using the correct string
index.
- Shell
- OS
=> Fix cherry pick preview

README.md, conf.d/forgit.plugin.fish, forgit.plugin.zsh
While we can see the compact diff in the preview window on `gd`, I find it useful to see the complete file when entering the diff. Set the diff context to 10000 for this purpose.
Before:
After:
Furthermore, display the diff range in the fzf prompt to see what we're looking at. With the normal `git diff` this is part of the diff output anyway, but with `diff-so-fancy` it's not, so this should be useful.
Before:
After:
- Shell
- OS
=> Improve forgit::diff

conf.d/forgit.plugin.fish, forgit.plugin.zsh
The git rebase command needs to be passed the parent commit of the one
you want to edit. When selecting a commit interactively via fzf, it
makes sense to automatically pass the parent commit of the selected one.
Within fzf it's otherwise quite hard to find the parent commit by hand
if you have found your commit via an fzf search string.
- Shell
- OS
=> grb: rebase on parent of the selected commit

conf.d/forgit.plugin.fish, forgit.plugin.zsh
The pager used on fzf enter key binding commands was hardcoded to `LESS='-r' less`. Transfer this to a variable in order to reduce code duplication and make it configurable.
Since the other pager variables were not part of the documentation I did not add this new variable either.
- Shell
- OS
=> Add variable FORGIT_ENTER_PAGER

conf.d/forgit.plugin.fish, forgit.plugin.zsh
Git stashes are named `stash@{x}`, which contains the fzf placeholder `{x}`. In order to support passing stashes as arguments to `forgit::diff`, we have to prevent fzf from interpreting this substring by escaping the opening bracket.
Before:
After:
- Shell
- OS
=> Support stashes in forgit::diff

conf.d/forgit.plugin.fish
I added a bunch of "wraps" commands to our functions. This is basically a quick and easy way to get function completion for free. Users can now tab complete most commands that take an argument
=> Adding wraps to fish - adding way to gcb an existing branch

conf.d/forgit.plugin.fish, forgit.plugin.zsh
When we want to perform a cherry pick, we had to pass the target branch as an argument to `gcp`. Forgit, however, aims to make git selections interactive where possible. Hence it seems natural to select the target branch interactively as well.
This change implements a new function `forgit::cherry::pick::from::branch` which opens an interactive branch selector and then calls the existing `forgit::cherry::pick` on the selected branch. Since this seems a far more intuitive way of performing a cherry pick I re-assigned the `gcp` alias to the new function.
The original `forgit::cherry::pick` had to be modified slightly in order to get a useful return code from it. Functionality stayed the same, though.
Along with this change I added a new global variable `forgit_log_preview_options` to reduce …
=> Interactively select branch in gcp

forgit.plugin.zsh
Port @cjappl 's changes of #232 / d4b4ce39087a2dfe4812d54de7a9865fb2ba9855 to zsh/bash.
`gcb` can now be called with an existing branch as an argument.
- Shell
- OS
=> Add ability to checkout existing branch with gcb

conf.d/forgit.plugin.fish, forgit.plugin.zsh
fzf has the following exit codes:
0      Normal exit
1      No match
2      Error
130    Interrupted with CTRL-C or ESC
The forgit functions "log", "diff" and "stash show" are designed to display information, not to perform any action. Hence the fzf exit codes 1 and 130 should not be interpreted as errors, they are normal exit behavior. Exclude these error values and return 0 in these cases.
- Shell
- OS
=> Do not return an error in log, diff and stash show

bin/git-forgit
Setting the error option in bash bypasses error handling in the forgit functions, because the script immediatley exits in case of an error. Remove the option to make error handling possible. Bash scripts automatically return the exit code of the last statement, so standalone forgit will still return useful error codes.
- Shell
- OS
=> Do not "set -e" in standalone forgit

.github/workflows/ci.yaml
The Ubuntu 18.04 CI image is deprecated:
https://github.com/actions/runner-images/issues/6002
Switch to the new 22.04 image instead.
- Shell
- OS
=> GitHub actions: update to Ubuntu 22.04

.github/scripts/changelog.sh, .github/scripts/tag.sh, .github/workflows/ci.yaml, .github/workflows/release.yaml, .github/workflows/tag.yaml
This PR adds a GitHub action for automatically creating a GitHub release for each tag (refs #233).
The action is executed on every tag and creates a GitHub release. The release contains a .tar.gz asset and a changelog consisting of all commit messages since the previous tag. Commits with a commit message starting with "Meta" are excluded from the changelog.
I tested this action on my forgit fork and you can see a generated changelog here:
https://github.com/carlfriedrich/forgit/releases
- Shell
- OS
=> Automatic releases

.github/workflows/ci.yaml, README.md, bin/git-forgit, conf.d/bin/git-forgit, conf.d/forgit.plugin.fish, forgit.plugin.zsh
This is something I wanted to do for quite a while, and during the last days I finally had some time to check out how to do it right (at least that's what I hope 😁).
I labeled this a draft, because this is kind of a new direction for forgit and I would like to discuss if we can all agree on this first, or if you have any other ideas how to improve this suggestion. If we actually can agree on it, I will adapt the documentation before merging this.
What this patchset basically does is move the actual forgit functionality from the shell plugin (`forgit.plugin.zsh` / `forgit.plugin.fish`) to the standalone forgit executable script (`git-forgit`). This has the following advantages:
1. We don't have to maintain two different forgit implementations for two different shells (zsh/fish) anymore.
2. …
=> Move implementation to standalone forgit

bin/git-forgit
When using `glo` (`forgit::log`) we can press `Enter` to show the changeset of the selected commit. The presentation, however, is rendered using the basic `git diff` command. We have a much more user friendly diff command `gd` (`forgit::diff`) right in forgit, though. Use this instead.
Fixes #217.
- Shell
- OS
=> glo:: use forgit::diff when entering a commit

bin/git-forgit
MacOS's sed variant obviously does not parse '\t' as a tabstop per default. Replacing it with a literal tabstop to make this work.
Fixes #245
- Shell
- OS
=> Fix forgit diff displaying renames on MacOS

.github/workflows/tag.yaml
The COMMIT_KEY secret contains a private SSH key. The associated public key has been added as a deploy key in the GitHub project. See: https://docs.github.com/en/developers/overview/managing-deploy-keys#deploy-keys
This is necessary to make commits done by github-actions able to trigger further github-actions. See:
https://stackoverflow.com/q/60418323/3018229.
- Shell
- OS
=> Meta: GitHub tag action: add commit key

bin/git-forgit
Noticed there was a change recently that broke the ability to pass in an input branch to `gcp`.
This change is the following:
- Fix faulty logic that just led to a `git checkout -b` being called when you pass in an argument to `gcp`
- If an argument was passed in, check if it is a valid branch, if so, set the `input_branch` var
- If `input_branch` is set, use it to do the cherry pick, as opposed to the first FZF selection.
PLEASE HELP ME REVIEW THIS, @carlfriedrich and @wfxr. I am such a bash syntax newbie, I don't know if I'm writing bad code 😄 
- Shell
- OS
=> Provide an input branch with gcp again

README.md, bin/git-forgit, conf.d/forgit.plugin.fish, forgit.plugin.zsh
Added an interactive git stash push selector, that works similar to `forgit::add`. The alias for it is `gsp`. I thought about passing arguments to the command to be able to use e.g. `-m "name"` to be able to name the stash entry, but had no luck implementing this so far. If anyone has an idea, let me know and I'll update my PR. From my perspective we could merge this PR without this additional feature. 
This closes #243 
https://user-images.githubusercontent.com/88739791/204108329-c8846a1b-3dbc-411a-be13-873e2d9bf39e.mp4
- Shell
- OS
=> Feature: Added git stash push selector

bin/git-forgit
Some systems do not have /bin/bash. e.g., Alpine and NixOS. This change allows the user to provide one's own path of bash to fzf. It solves the error `fork/exec /bin/bash`.
Note that `fzf --preview 'xxxx'` essentially executes `$SHELL -c 'xxxx'`, so I tested on bash, zsh, and fish forgit::blame and it worked.
- Shell
- OS
=> feat: allow overriding default $SHELL /bin/bash

bin/git-forgit
Closes #253. Essentially the idea is this: 
- When cherry picking a group of commits, most of the time you want to cherry pick oldest to newest. This means you have the lowest chance of having a conflict or error
- when reverting a commit. You most often want to revert from newest to oldest. Similarly prevents errors
This commit does that, based on the wonderful suggestion on how to do that from @carlfriedrich in the linked ticket (#253). 
Best reviewed with turning whitespace off, as I added some in there. I also made a few small stylistic changes so these two functions mirrored each other more closely, as fundamentally they do similar things (get a list of commits, and feed them to the function).
TO TEST:
- Try to revert one commit
- Try to revert 3 commits in all orders  - the …
=> Ensure that `grc` and `gcp` always have the correct ordering, regardless of how they were input

bin/git-forgit
Closes #254 
`grh` didn't work if you were in a subdirectory. From the issue ticket:
"
Steps to repro
Change a file
git add the file
mkdir somesubdirectory && cd somesubdirectory
grh
Expected:
File show up in forgit, if you tab select them they get unstaged
Observed:
Nothing to unstage.
"
This should fix that.
- Shell
- OS
=> Adding the ability to grh from a subdirectory

conf.d/forgit.plugin.fish
In the fish wrapper, assume forgit-git to be in vendor_conf.d/bin in case it can not be found in conf.d/bin. This fixes forgit not working with fish when located in /usr/share/fish/vendor_conf.d, as is the case with the [forgit](https://aur.archlinux.org/packages/forgit) and [forgit-git](https://aur.archlinux.org/packages/forgit-git) AUR packages. The location at conf.d is kept (and stays the default), so forgit does not break compatibility with fish plugin managers, such as fisher.
Closes #270
- Shell
- OS
=> Fish: Allow git-forgit in vendor_conf.d

bin/git-forgit
Added escaped quotes around the file variable inside the preview string in `_forgit_add()` to prevent word splitting on files that have spaces in their file path. As a result such files do now generate a preview as expected.
Closes #263
- Shell
- OS
=> Fixed: Untracked files with spaces in the path do not show a preview with ga

README.md, completions/git-forgit.bash
This is my shot for porting @cjappl 's changes of #231 to bash. Not every forgit function supports arguments at the moment, but at least for the ones that support it completion is a useful thing, so I added it for all functions at once, just like in fish.
@wfxr What do you think? And do you know how this could be implemented for zsh?
Tested all completions in bash.
- Shell
- OS
=> Add bash completions for forgit functions and aliases

bin/git-forgit
Fixes #264 
Only shows changes that are eligible for cherry-pick to the branch, not every commit. Also adds nice color to the output
Steps to test:
- Get two branches that have diverged (`thisBranch` and `otherBranch`
- `gcb thisBranch`
- `gcp otherBranch`
Expected:
- Only the commits in "otherBranch" that DO NOT appear in "thisBranch" appear in the fzf window
- If you cherry pick one of those commits, then `gcp otherBranch` again, it disappears from the fzf output (as it is successfully cherry-picked and not eligble for cherry-pick again.
- Shell
- OS
=> Only show available cherry picks

conf.d/forgit.plugin.fish
Noticed there was another alias missing for fish. This is the last one :)
- Shell
- OS
=> Add alias gct for forgit::checkout::tag in fish

bin/git-forgit
Checkout/Add files in a single command in `_forgit_add` and `_forgit_checkout_file()` instead of processing each file individually with xargs. This has the following benefits:
1. It's faster
2. Prevents git from spamming "Updated 1 path from the index" for each file when checking out files
- Shell
- OS
=> Process files in a single command in ga & gcf

bin/git-forgit
**Bug**: `glo -- files` should show specified files only, but instead it shows all changed files.
**Fix**: There is a redundent blank in sed regex.
- Shell
- OS
=> fix: forgit::log can not match files

README.md
Saw #212 and thought I'd submit a PR instead of leaving the oh-my-zsh install instructions within an open issue :)
- Shell
- OS
=> #212 Include oh-my-zsh install instructions in README

bin/git-forgit
This had been fixed before in #189, but obviously the patch broke support for whitespaces in file names. That was fixed in #204, which in turn broke support for renames again.
Unfortunately we cannot support both cases together with the existing `xargs` implementation, because the arguments are interpreted either as one single file name (which breaks renames, because we have two files passed in this case) or as separate file names (which breaks whitespace support, because git would interpret each word of the file name as a separate file).
This patch moves away from `xargs` and stores the file names in a bash array instead. This makes it possible to pass them to `git diff` quoted one by one using the `"${array[@]}"` notation.
Test environment:
```shell
mkdir test && cd test
git init
touch …
```
=> Fix empty diff preview on renames

conf.d/forgit.plugin.fish
See #289 for the complete details
- Shell
- OS
=> Detect unexported variables in fish correctly (Fix #289)

bin/git-forgit
This is a follow-up to #266, which already switched to showing only available commits during cherry-picking. This patch does the same for the branch preview in `_forgit_cherry_pick_from_branch`.
- Shell
- OS
=> Only show available cherry picks in preview

bin/git-forgit
With the changes of #261 and #266 we accidentally broke the return value of `_forgit_cherry_pick`, which led to the loop in `_forgit_cherry_pick_from_branch` being terminated in the wrong cases. Fix this by moving all the post processing after fzf to a later call.
Also simplify the array population using a single line instead of a loop.
This should also fix #286 ("fatal: bad revision ''").
- Shell
- OS
=> Fix broken cherry picking

README.md, bin/git-forgit
The git behavior within forgit can now be customized via dedicated variables for each forgit command, e.g. `FORGIT_ADD_GIT_OPTS` is passed to the `git add` call within `ga`.
This should make #277 obsolete.
- Shell
- OS
=> Add git options for each forgit command

bin/git-forgit
Adding options to a command in a quoted variable as introduced in #292 causes problems in several cases unfortunately (e.g. git rebase interpreting an empty string argument as a remote, which leads to an error "unknown upstream ''").
Change the implementation in a way that each git command is stored in a shell variable, including the options, which is then evaluated.
- Shell
- OS
=> Fix git options

bin/git-forgit
When setting the IFS for a certain command only, the command must not be an assignment, otherwise both assignments are evaluated permanently (see https://unix.stackexchange.com/a/458901/317320).
- Shell
- OS
=> Fix temporary IFS settings

README.md, bin/git-forgit
Add keybinding `ctrl+y` for copying stash ID in `gss`.
Fixes #287.
- Shell
- OS
=> Add keybinding ctrl+y for copying stash ID in gss

bin/git-forgit
This was accidentally broken since 450615d4 due to a wrong git call.
Refs #301.
- Shell
- OS
=> Fix grc / forgit revert_commit

bin/git-forgit
The previous implementation had the problem that if IFS was not set before, it was set to an empty string after restoring, which is not the same as being unset. This broke grc / git forgit revert_commit, since "git revert" was being interpreted as the command name instead of command and argument.
The correct way is to check whether IFS is unset and, if so, unset it again afterwards.
See for reference:
https://unix.stackexchange.com/a/264947/317320
Fix #301.
- Shell
- OS
=> Use correct IFS store/restore mechanism

README.md, bin/git-forgit
Love the project! I'm using it to replace some scripts I'd hand rolled doing roughly the same thing!
However, I was hoping to use `checkout_branch` to quickly swap between recent branches. To do this I'd like to pass `--sort=-committerdate` to the `git branch` command to sort them by most recent commit.
- Shell
- OS
=> Allow configuration of checkout_branch branch command

conf.d/forgit.plugin.fish, forgit.plugin.zsh
It seems somewhere along the line `FORGIT_INSTALL_DIR` stopped getting exported. According to the README you can append it to your path to get access to `git forgit ...` commands however this seems to no longer work - this is an attempt to restore this functionality.
https://github.com/wfxr/forgit/blob/5642a1a7307c17d452271b9e7aaa8bcec6a47f53/README.md?plain=1#L174
- Shell
- OS
=> Restore support for appending FORGIT_INSTALL_DIR to path

bin/git-forgit
Allow passing parameters to forgit::reset::head in the same way we already do for most other functions.
- Shell
- OS
=> Allow passing parameters to forgit::reset::head

bin/git-forgit
Noticed that we could also allow passing parameters to forgit::branch::delete and forgit::stash::show. 
- Shell
- OS
=> Allow passing parameters for more functions

README.md, completions/_git-forgit, completions/git-forgit.zsh, conf.d/forgit.plugin.fish
The implementation follows the existing bash completions with a few differences:
I've split the implementation into two files: _completions/\_git-forgit_ for usage of forgit as a git subcommand and _completions/git-forgit.zsh_ for usage of forgit as a shell plugin. The reason for this is that zsh's `autoload` does not load the files on shell start, but dynamically the first time a completion is needed. Having the `compdef` commands that bind the completions for the shell plugin in the main file would lead to the completions becoming available after `git forgit` has been completed for the first time. Because this behavior would be inconsistent and confusing, I've placed them in a separate file that has to be sourced explicitly. _completions/\_git-forgit_ simply has to be placed in a …
=> Added completions for zsh

README.md, bin/git-forgit
Add a keybind `alt-e` to allow open current file in default editor. This will facilitate doing diff and modify loop. 
- Shell
- OS
=> feat: add a keybind to open current file in editor

bin/git-forgit
Most functions try to pass parameters directly to git and exit early when successfull. `_forgit_clean` is an exception to this, as it currently only uses the arguments to determine the target files. Our completions use `_git-clean`, which completes untracked files, but `gclean -f FILE` currently opens the file picker.
I've added a line to allow an early out for `_forgit_clean`.
- Shell
- OS
=> Make glcean parameters consistent with other functions

README.md
Docs with an example of using a config var to customize `gcb`
- Shell
- OS
=> docs: example of using config vars to sort git branch

bin/git-forgit
Most of forgits functions allow to invoke git directly when arguments were passed. In most of these functions we only return early when the git command that is executed returns successfully. This hides error messages from the user. As discussed with @carlfriedrich in #316, I've modified this behavior to also return early when the git command was not successful, so we're transparent about gits error messages and return values. Because `gbl` and `gclean` allow passing arguments to the git command that is invoked when we don't return early, I've modified their behavior to only invoke git directly (and return early) in the case that non flag arguments were passed.
I've also modified `gclean` to use the `-q` flag instead of piping it's output to /dev/null.
This PR supersedes #316.
- Shell
- OS
=> Do not hide error messages when trying to return early

README.md
The note here is redundant because it is explained in more detail in the [git integration](https://github.com/wfxr/forgit#git-integration) section.
=> Docs: Removed note about using forgit as a git sub-command from the 'tips' section

bin/git-forgit
git natively supports `-` as an argument to `git switch` and `git checkout`. It is shorthand for `@{-1}`, which is a way to refer to the last branch you were on.
forgit used to interpret `-` as a branch name, detect that it does not exist yet and create a new one with this name, which does not work.
Add a check whether `-` is passed on the command line and do not create a new branch in this case
- Shell
- OS
=> checkout_branch: support "-" argument

bin/git-forgit
Escaped variables in _forgit_add() and _forgit_diff() to fix opening files that contain spaces.
Added a separate sed command for retrieving a file in _forgit_diff() that correctly handles renamed files (when opening the editor while diffing staged changes).
- Shell
- OS
=> Fix opening files in editor when path contains spaces or file was renamed

README.md
This updates the documentation for using `forgit` as a subcommand of `git` by removing the use of the `export` built-in. For all intensive purposes, `PATH` [is already exported](https://unix.stackexchange.com/a/138557). If it weren't, then executing a subprocess (ex. `system("bash ...")`) would always fail since `PATH` wouldn't be copied from parent to child. This simplifies the export line accordingly.
- Shell
- OS
=> Remove extraneous PATH export

README.md
Just to enable a new `##brew` subheader to explain a bit more about that installation.
I realized our top level header was H3 instead of H1. Remove some `#` to simplify.
=> README tweak: decrease level of headers

README.md
Added more explicit instructions, now that I know how our `brew` installation process works.
While I was there, I moved AUR and Fig to be subheaders of `Installation`
=> README: Add more explicit instructions for brew, fix headers for AUR, Fig

.github/workflows/brew.yaml
This workflow was found here:
https://github.com/dawidd6/action-homebrew-bump-formula
This should be very similar to our AUR workflow, which can be seen here:
https://github.com/wfxr/forgit/blob/ab7400ddb37c758b8247ce0884cd2283a873e258/.github/workflows/aur.yaml#L1-L20
I am writing an email to @wfxr asking him to add a BREW_TOKEN to our secrets with the appropriate permissions so this can run :). This change should not be submitted until he has confirmed the BREW_TOKEN has been added to our secrets.
=> Add new workflow to update homebrew formula on release

.github/workflows/brew.yaml
This is a rehash of #341 but with the correct base.
This workflow was found here:
https://github.com/dawidd6/action-homebrew-bump-formula
This should be very similar to our AUR workflow, which can be seen here:
[forgit/.github/workflows/aur.yaml](https://github.com/wfxr/forgit/blob/ab7400ddb37c758b8247ce0884cd2283a873e258/.github/workflows/aur.yaml#L1-L20)
Lines 1 to 20 in [ab7400d](https://github.com/wfxr/forgit/commit/ab7400ddb37c758b8247ce0884cd2283a873e258)
name: AUR 
on: 
workflow_run: 
workflows: 
- "Release" 
types: 
- completed 
jobs: 
aur: 
runs-on: ubuntu-latest 
steps: 
- name: Publish 
uses: zokugun/github-actions-aur-releaser@v1 
with: 
package_name: forgit 
aur_private_key: ${{ secrets.AUR_PRIVATE_KEY }} 
aur_username: ${{ secrets.AUR_USERNAME }} 
aur_email: ${{ …
=> Add new workflow to update homebrew formula on release 

bin/git-forgit
* Use short flags for `sort` command
* Remove `-n` flag for `nl` command. The numbers in the selection list won't be aligned anymore, but no information is lost.
The current arguments are only presented in GNU's coreutils.
- Shell
- OS
=> fix: keep the script compatible with Busybox applets

forgit.plugin.zsh
Minor fix to avoid variables used locally in `forgit.plugin.zsh` to be exported in to the global namespace.
- Shell
- OS
=> fix: avoid polluting global namespace

completions/git-forgit.fish
fish's builtin git completion automatically registers `git-forgit` completions as completions for `forgit` subcommand of git. Therefore this PR provides completions for both formats `git-forgit` and `git forgit`.
Simple subcommands get the completion list from `__fish_git_*` functions, while others requiring more than 1 `__fish_git_*` completion sources reuse the completion items from the corresponding git commands.
- Shell
- OS
=> feat(completions): add completion for fish

conf.d/forgit.plugin.fish
* use `status dirname` builtin to save 1 dirname call
* use builtin `test` function instead of `[` syntax
* use local scoping for INSTALL_DIR variable (and make it lowercase to indicate such change)
Ref: https://fishshell.com/docs/current/cmds/test.html
- Shell
- OS
=> fix(fish): clean up variables

.github/workflows/ci.yaml, .github/workflows/release.yaml, .github/workflows/tag.yaml
Resolve deprecation warnings for GitHub actions, see https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
- Shell
- OS
=> chore(gha): Update actions/checkout from v3 to v4

bin/git-forgit
Our sed command for removing the short status (e.g. [M]) from gits
output to extract the file name with \_forgit\_diff matched until the
last ']' character in the line due to sed being greedy. This created
issues with file names that contain a ']' character.
To fix this, I made sure that only the short status is removed by sed,
independently of the file name.
Fixes #353
- Shell
- OS
=> Fix diff preview and edit for files with a ']' character in their name

conf.d/forgit.plugin.fish
* Switch from aliases to abbreviations, as I suggested in https://github.com/wfxr/forgit/pull/344#issuecomment-1930072329
* `string collect` returns 1 on empty argument, so it's used here to avoid repeating `if else end` blocks. Another benefit is that the output of `string collect` is ensured to be a single string. From `string --help`:
> `string collect` collects its input into a single output argument, without splitting the output when used in a command substitution. This is useful when trying to collect multiline output from another
command into a variable. Exit status: 0 if any output argument is non-empty, or 1 otherwise.
This PR is marked as breaking change, since abbr behaves differently from alias. It can only be used in the interactive command line (so putting `exec glo` into …
=> feat(fish): use abbr instead of alias

bin/git-forgit
We've removed deferred code and replaced it with functions instead. This includes all usages of `eval`. There are four different types of functions we've added:
1. Preview functions (e.g. `_forgit_add_preview`) that are responsible for the `fzf` preview
1. Edit functions (e.g. `_forgit_edit_add_file`) that are responsible for editing files with your `$EDITOR` from within forgit functions
1. Git functions (e.g. `_forgit_git_add`) that make simple git commands reusable
1. Utility functions (e.g. `_forgit_yank_sha` or `_forgit_quote_files`) that were created either out of necessity or implement functions that were previously stored as deferred code in variables.
We've exposed some of these functions as forgit commands. This includes all preview and edit functions and some of the utility …
=> Reduce deferred execution

bin/git-forgit
In bash 3.2 uninitialized arrays contain one entry: an empty string, whereas in modern versions of bash they do not contain any entry. I could not find documentation on this but the behavior can be verified by running the following script:
```sh
local arr
echo "length=${#arr[@]}"
echo "content=${arr[@]}"
```
On bash 5.2.26 this prints
```
length=0
content=
```
On bash 3.2.57 this prints
```
length=1
content=
```
This PR makes sure the `$commits` and `$files` arrays are explicitly initialized as empty arrays to allow git to fall back to diffing local changes instead of trying to diff against a revision with a name of an empty string.
Fixes #373
- Shell
- OS
=> Fix _forgit_diff on macOS

conf.d/forgit.plugin.fish
In our homebrew formula, we were replacing this line in the installation:
```
Replace this:             'set -x FORGIT "$FORGIT_INSTALL_DIR/bin/git-forgit"',
with this     :             "set -x FORGIT \"#{opt_prefix}/bin/git-forgit\""
```
However, later in the fish script, we ignored that, just basing it directly off of the install dir:
```
alias git-forgit "$FORGIT_INSTALL_DIR/bin/git-forgit"
```
This makes sure that we always line up and don't have `fish: Unknown command: /opt/homebrew/share/conf.d/bin/git-forgit
- (line 1):` as in #377 
Fixes #377 
- Shell
- OS
=> Fix bug where homebrew replacement wouldn't work

bin/git-forgit
The `$_forgit_preview_context` variable used in the deferred code block for generating the preview of `_forgit_diff` was not quoted. No known bugs were caused by this, just making sure we follow best practices.
This is a follow-up to #326 and was originally discussed [here](https://github.com/wfxr/forgit/pull/326#discussion_r1527607723).
- Shell
- OS
=> Refactor: Quote variables in preview of _forgit_diff, _forgit_reset_head & _forgit_cherry_pick_form_branch

bin/git-forgit
The preview for branches (when using `gbd` or `gcb`) did not work for branches that have the same name as a file in the repository.
The preview creates the following error message when adding a branch called 'LICENSE' to this repository and trying to preview it:
```
fatal: ambiguous argument 'LICENSE': both revision and filename                                                                                     
Use '--' to separate paths from revisions, like this:                                                                                               
'git <command> [<revision>...] -- [<file>...]'
```
This PR fixes this behavior by separating files and revisions with '--' as git suggests, while leaving the files blank to keep matching all files.
- Shell
- OS
=> Fix branch preview for branches that have the same name as a file

bin/git-forgit
We sometimes capture multiline output in an array. We used to do so directly, while setting IFS to "\n" to control splitting. This has the downside that bashs glob expansion will be invoked.
I think the original reason we did use this technique was that it does work in both zsh and bash. Since we always execute bin/git-forgit in bash now, this is not necessary anymore. We can use `read -r` in such cases to add each line to the array without glob expansion. This is the idiomatic way to do so and recommended in [shellcheck 2207](https://www.shellcheck.net/wiki/SC2207). In my personal opinion this is also a cleaner and more straightforward approach than setting and resetting `$IFS`.
- Shell
- OS
=> Refactor: Do not ignore shellcheck 2207

bin/git-forgit
Our pager variables, e.g. `$_forgit_blame_pager` used to be in deferred code blocks that were evaluated with `eval`. Since we've removed the usage of `eval` in #326, variables in the pagers no longer get expanded, as is the case with #380.
In this specific case, evaluation is what we want and deferred code is unavoidable if we do not want to cut down on existing functionality, since the pagers are defined outside forgit (either in the git config or in an environment variable). The most straight forward approach to solving this would probably be to introduce `eval` everywhere we use the pager variables, e.g.
```diff
- "$FORGIT" exec_diff "${commits[@]}" -U"$diff_context" -- | $_forgit_diff_pager
+ "$FORGIT" exec_diff "${commits[@]}" -U"$diff_context" -- | eval "$_forgit_diff_pager"
``` …
=> Fix: Pager variables are not evaluated

bin/git-forgit
We're currently using `--pathspec-file-nul` in `ga`, `gsp` and `gcf`. This option is not available in older versions of git, such as the current release in the Ubuntu repositories (2.25.1). This PR removes the usage of `--pathspec-file-nul` in favor of storing the file names passed to the git command in an array instead of a string.  
This PR is based on #326. I will rebase and mark it as ready for review, once #326 is merged.
Fixes #328
- Shell
- OS
=> Fix issues with `ga`, `gsp` & `gcf` with git 2.25.1

bin/git-forgit
Shellcheck [2206](https://www.shellcheck.net/wiki/SC2206) and [2068](https://www.shellcheck.net/wiki/SC2068) have been disabled in `_forgit_ignore` for a very long time. The code that triggers the shellchecks was added in ce240ac before the shelllcheck action had been added. The shellceck for the lines in question got disabled in c14ce93. The commit message does not state why, but I'm guessing that this has been done simply to make the CI pass. I do not think disabling the shellchecks is necessary here. I've implemented the fixes shellcheck suggest and I could not find any issues with it.
- Shell
- OS
=> Do not disable shellcheck 2206 and 2068 in _forgit_ignore

bin/git-forgit
`_forgit_stash_push`, `_forgit_revert_commit` and `_forgit_blame` passed some fzf options as arguments directly instead of defining them in the `$opts` variable, as we do everywhere else. This change makes these functions consistent with the rest of the code base and additionally allows overriding said options with the respective `$FORGIT_*_FZF_OPTS` environment variables.
- Shell
- OS
=> Move fzf options into $opts variables

README.md, bin/git-forgit
`gclean` is the only command that does not display a preview. I sometimes find myself exiting `gclean` just to check the content of a file before deleting it. Being able to have a last peek at a file before removing it does sound like a good idea in general to me.
- Shell
- OS
=> Add a preview to _forgit_clean

bin/git-forgit
Previously when using gsp without any local changes, an empty file picker would open. Check if any files can be stashed and show a message instead when this isn't the case.
Fixes #369
- Shell
- OS
=> Fix: Early out from _forgit_stash_push when no files can be stashed

README.md
- **Fix some typos and wordings in README.md**
- **Fix headers style**
- **Fix exemplī grātiā usage (Latin)**
- Shell
- OS
=> typos suggestion

bin/git-forgit
The order of the arguments passed to git blame in \_forgit\_blame\_preview has been changed in bfffda6, putting `--date=short` as the last argument instead of the first. This caused it taking precedence of anything defined in $FORGIT\_BLAME\_GIT\_OPTS. This PR restores the order of the arguments to what they were before bfffda6.
- Shell
- OS
=> Fix: --date option in gbl can not be overridden anymore

bin/git-forgit
We allow disabling the `--graph` option of `git log` when `$FORGIT_LOG_GRAPH_ENABLE=false` is set. This PR makes sure that this is also the case in `_forgit_revert_commit` that has been ignoring this until now.
- Shell
- OS
=> Allow disabling --graph with FORGIT_LOG_GRAPH_ENABLE=false in grc

bin/git-forgit
`gsp` only works when executing it from the repository's root directory. This commit fixes this by passing the root directory to the `git ls-files` command we use to determine the files that can be stashed, similarly to how we do it in \_forgit\_reset\_head.
- Shell
- OS
=> Fix: gsp does not work outside the root directory

bin/git-forgit
When trying to open a file from gd in $EDITOR (alt + e) the wrong file was being opened when the command wasn't executed from the repository's root directory.
Fixes #392
- Shell
- OS
=> Fix: Opening files from diff line when not in project root

.github/dependabot.yml
Currently there still are actions that need to be updated due to the deprecation of Node.js 16 on runners: https://github.com/wfxr/forgit/actions/runs/8903375722
By adding a dependabot configuration the GitHub actions used by workflows of this repository will stay up to date.
All configuration options are documented on [https://docs.github.com](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file).
- Shell
- OS
=> ci: add dependabot update for GitHub actions

bin/git-forgit
Git escapes special characters in it's output when `core.quotePath` is true or unset. Git always expects unquoted file paths as input. This leads to issues when we consume output from git and use it to build input for other git commands. This commit ensures we always feed unqoted paths to git commands. The `_forgit_list_files` function is introduced to handle usage of git ls-files with the -z flag, which ensures unquoted paths. It replaces the direct calls to git ls-files in `_forgit_reset_head`, `_forgit_stash_push` and `_forgit_checkout_file`.
In `_forgit_add` the current approach of using colors to separate unstaged from staged files is replaced with a call to `_forgit_ls_files` with the appropriate flags to only list unstaged files.
In `_git_reset_head` the -z option is added to the …
=> Fix special characters in file names

bin/git-forgit
I found that all untracked files will always be listed recursively after `forgit add` is called. This is annoying when there are some untracked directories with lots of files in a repo. Useful information will be flushed out by these untracked files. This patch removed the `-u` option from `git status` to just list the untracked directory itself.
- Shell
- OS
=> refactor: remove -u option from git status in forgit add

README.md, bin/git-forgit, completions/_git-forgit, completions/git-forgit.bash, completions/git-forgit.fish, conf.d/forgit.plugin.fish, forgit.plugin.zsh
I do not use `git reflog` very often but when I do, I really miss forgits ergonomics - time to fix that!
The `git reflog` command is very similar to `git log` in almost every way, so I kept my implementation very close to `_forgit_log`. I was even able to reuse the `log_enter` and `log_preview` functions for it. The usage in forgit is exactly the same as with `_forgit_log`.
- Shell
- OS
=> Feature: Add interactive git reflog

.github/scripts/changelog.sh, .github/workflows/release.yaml
The latest forgit release did not contain any release notes, because the only commit since the previous release had the `Meta` prefix in its git summary, and we do not include these commits in the release notes.
In such a case we should not create a release at all, since we do not have any code changes. I fixed this in the GHA jobs and tested it in my private fork. Will merge this next week if no complaints come in.
- Shell
- OS
=> Meta: do not create release when there are no public changes

.editorconfig, bin/git-forgit, completions/_git-forgit, completions/git-forgit.bash
- Supoorted by many editors to maintain consistent coding style
- For more information on `.editorconfig` check out https://editorconfig.org/
Closes #403
- Shell
- OS
=> Meta: add an .editorconfig and apply it to the codebase

bin/git-forgit
The key binding `alt-e` for editing a file in diff and add was not working properly on recent versions of fzf. As its documentation suggests, we should replace `execute-silent` with `execute` since we need to switch to a new screen and handle both input and output.
> fzf switches to the alternate screen when executing a command. However, if the command is expected to complete quickly, and you are not interested in its output, you might want to use execute-silent instead, which silently executes the command without the switching.
- Shell
- OS
=> fix: fix edit file key binding (alt-e) in diff and add

README.md
We've added an optional dependency for `tree` with #383, but never mentioned this in the README.
- Shell
- OS
=> Meta: add tree as an optional dependency

README.md, bin/git-forgit, completions/_git-forgit, completions/git-forgit.bash, completions/git-forgit.fish, conf.d/forgit.plugin.fish, forgit.plugin.zsh
Use the new command in git log enter. This fixes the display of diffs for merge commits.
Fixes #416.
- Shell
- OS
=> Feature: add forgit show command

bin/git-forgit
Removing `_forgit_ignore_clean`. As discussed in #407, this function has been unused for a long time.
Closes #407
- Shell
- OS
=> Refactor: Remove _forgit_ignore_clean

README.md, bin/git-forgit, conf.d/forgit.plugin.fish, forgit.plugin.zsh
Adds an interactive .gitattributes generator that works exactly the same as the one we already have for .gitignore. I've refactored the functions used in `_forgit_ignore()`, so they can also be used for `_forgit_attributes()`. When testing, it's a good idea to also test that `gi` still works as it did before.
~~Marked this as a draft, because I first want to sort out what to do with #407 and refactor `_forgit_ignore_clean` if necessary.~~
Closes #405
- Shell
- OS
=> Feature: Add interactive git attributes generator

bin/git-forgit
If non-option arguments are passed to `git forgit rebase`, pass them
through directly to `git rebase`, without launching the interactive
selector, just like we do for other forgit commands.
Along with this, I removed the possibility to pass files to rebase.
IMO there is no need to pass files to rebase. I assume this was a copy-paste
error when the rebase function was introduced in the first place.
- Shell
- OS
=> Allow passing arguments to git rebase

conf.d/forgit.plugin.fish
In fish shell, `git-forgit ignore` and `git-forgit attributes` maped to the same abbreviation `gi`. This pr changes the behavior as default on bash , zsh where `git-forgit ignore` is `gi` and `git-forgit attributes` is `gat`
- Shell
- OS
=> feat(fix): Fish shell git ignore and git attributes are maped to same abbreviation

.github/workflows/ci.yaml
GitHub has deprecated the `ubuntu-20.04` runnner as outlined [here](https://github.com/actions/runner-images/issues/11101). This PR updates the CI to always include the latest available Ubuntu image (currently `ubuntu-24.04`) and removes `ubuntu-20.04`.
We should probably merge this PR before anything else, to prevent the CI from failing when merging new PRs.
- Shell
- OS
=> Meta: use latest ubuntu image for ci

bin/git-forgit
When using `_forgit_checkout_branch` we currently only create a local branch when the remote of the branch is called `origin`. I often work with multiple remotes and also need to push commits to 
remotes other than `origin`. I do not see any harm in creating a local branch when the remote branch is not coming from `origin` (please correct me if I'm wrong). To allow this, this PR is
introducing wildcards to the corresponding checks instead of specifically checking for `origin`.
- Shell
- OS
=> Fix: create branch when checking non origin remote

forgit.plugin.zsh
Closes #435
Fish does not seem to be affected by this issue, so no changes necessary there.
- Shell
- OS
=> Fix: prefix all commands in forgit.plugin.zsh

bin/git-forgit
Similar to #422, this removes the option to pass files to the fixup and squash functions. I don't think this serves any purpose there either and was simply a copy/paste error too.
- Shell
- OS
=> Refactor: Do not pass files to fixup and squash

README.md, bin/git-forgit, completions/_git-forgit, completions/git-forgit.bash, completions/git-forgit.fish, conf.d/forgit.plugin.fish, forgit.plugin.zsh
Because we allow editing commits with (squash) and without (fixup) editing the commit message, it makes sense to me to also **only** edit the message of a commit, which is something I do regularly. `git commit` has the `--fixup=reword:<COMMIT>` option that I make use of here. Unfortunately, this implementation cannot share the `_forgit_edit_commit` function that we use for fixup and squash because the syntax with reword is a bit different:
1. With reword, git expects `--fixup=reword:<COMMIT>` whereas with fixup and squash, it does not expect the colon.
2. With reword, we do not want to skip the editor when creating the commit.
- Shell
- OS
=> Feature: add interactive reword selector

bin/git-forgit
This reverts commit 3f694f6e99c8b6d63dc3f702733ec9e728c31728 and adds the same filtering option to reword.
- Shell
- OS
Fixes #446
=> Fix: allow filtering by files in fixup, squash and reword

bin/git-forgit
Pretty much the same as #451 but for `git add`. Allows e.g., staging only part of a file with `ga -p`.
- Shell
- OS
=> Feat: allow passing arguments to git add

bin/git-forgit
Instead of using `git stash show` in the `enter` binding of the `stash_show` command, use `forgit show`. This allows forgit to show the stash in the same interactive way it shows other commits (e.g. on `forgit log`), with the same context and formatting options.
- Shell
- OS
=> Feat: Use forgit show in stash_show enter

bin/git-forgit
Thanks @carlfriedrich for your insights provided in https://github.com/wfxr/forgit/issues/458#issuecommentj3089130866. I've implemented this as suggested, including the preview for normal mode, for which I simply used our existing directory view:
Pass the value of `git config status.showUntrackedFiles` to the `git status` command we run in `_forgitladd`, defaulting to `all` when unset.
Additionally correctly handle directories in `forgit_add_preview` for the case when `status.showUntracked` is explicitly set to `normal`.
You can see the different modes in action here:
<a href="https://asciinema.org/a/iO5purJ2PFkRjcl5CoBwILSXj" target="_blank"><img src="https://asciinema.org/a/iO5purJ2PFkRjcl5CoBwILSXj.svg" /></a>
- Shell
- OS
Fixes #458
=> Fix: files in untracked directories are not shown in git add
