forgit.plugin.sh

I've copied your `git stash` viewer implementation for zsh and make it works in bash.

Add `git stash` viewer for bash

---

forgit.plugin.sh
forgit.plugin.zsh

Control aliases creation using `$FORGIT_NO_ALIASES`.

Enable not defining aliases at all

---

forgit.plugin.fish
forgit.plugin.zsh

Hi @wfxr,
I opened #42 but had some time on my hands so figured I'd take it on.
I'd love someone else to test this out, but it is working great on my end! You'll notice it looks very familiar to zsh/sh.
The only functionality I added was checking for fzf before sourcing, at the very top of the file

Fish shell support

---

README.md
forgit.plugin.fish
forgit.plugin.zsh

As promised, here is the README update, feel free to check my fork for how it looks now, basically added the fish sections!
I also added a check for fzf as well as a helpful warning message if it's missing. This is something I did for the fish version and figured it'd be nice if they matched!

Fixed readme and added fzf check to zsh to be the same as fish version

---

forgit.plugin.zsh

caused by https://github.com/wfxr/forgit/commit/325e98cd03c71d7e280b7259ff7793cec0afd726#diff-b3f00b3beaf9e81cc8bee82da7fc86faR6

fix shell error in forgit.plugin.zsh

---

.github/pull_request_template.md

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context, such as the description of the bug you're trying to fix. 
Adds a new PR doc so we can get more information from new contributors when they do a PR!
Fixes # (issue)
* OS:
@cjappl @wfxr

Adding a PR template

---

forgit.plugin.fish

Added fish support for pager
Fixes # (issue)
#51 
* OS: Mac OSX
@cjappl @wfxr

Added git pager support

---

forgit.plugin.fish

Getting up to parity with zsh version #58 
Also fixed a bunch of issues the fish side of things had with whitespace! so glad I checked this out, I was not handling things correctly.
- Shell
- OS

Fix path fish

---

forgit.plugin.zsh

#66 
Improve diff preview on untracked files for `ga`.
- Shell
- OS
@cjappl Please help sync the fish version.

Improve diff preview on untracked files for `ga`.

---

forgit.plugin.fish

added untracked files to fish forgit-add

---

forgit.plugin.fish

Closing the loop on #79 for fish!
- Shell
- OS

Feature toggle log graph, fish

---

forgit.plugin.fish

Brought fish up to speed with #74. 
- Shell
- OS

Preview error

---

README.md
forgit.plugin.fish

Fixed #85 for fix
- Shell
- OS

added glo slice to fish, warning about fish 3.1

---

forgit.plugin.fish
forgit.plugin.zsh

fixed gcf, and a bunch of other things. Added git status before returns

---

README.md

I updated the README with btab information for new users! #97

added toggle mark move down to README

---

forgit.plugin.zsh

The existing script handles the `core.pager` attribute, but does not
account for the `pager` attribute in git-config. Tools like
`diff-highlight` which ship with git recommend using the `pager`
attribute, and provide beautiful diffs.
I've made minor changes in the script to use these configuration
parameters if they are defined.
Ref: https://github.com/git/git/tree/master/contrib/diff-highlight
Description is part of the commit message above. This change lets me use diff-highlight tool to show beautiful diffs.
- Shell
- OS

Handle .gitconfig pager attribute.

---

forgit.plugin.fish

added fish support for git show+diff pager

---

README.md
forgit.plugin.zsh

Add cherry-pick support

---

forgit.plugin.fish

git cherry working in fish shell

---

README.md
forgit.plugin.zsh

Add rebase function

---

conf.d/forgit.plugin.fish

Git rebase for fish shell

---

README.md

Fix installation documentation using fisher

---

README.md
conf.d/forgit.plugin.fish
forgit.plugin.zsh

Fish checkout branch - updated internal function names to checkout::file and checkout::branch

---

.pre-commit-config.yaml
LICENSE
README.md

Add license content as `mit-license.org` suggested.

---

README.md
forgit.plugin.zsh

Add a way to personalized git log format. Personaly i prefer something like
`%C(auto)%h%d %s %C(blue)%an %C(green)%C(bold)%cr`
I work with black background screen. so black on blackl is not usefull. 
- Shell
- OS

Glo format

---

README.md
forgit.plugin.zsh

Sorry i make a mistake into default value.

Fix reset parameter in FORGIT_LOG_FORMAT default value

---

conf.d/forgit.plugin.fish

Implemented log format for fish

---

conf.d/forgit.plugin.fish

GCO for fish

---

conf.d/forgit.plugin.fish

Moved git checkout branch to parity with zsh. Check out remote branch when possible

---

conf.d/forgit.plugin.fish

fixes #168
See https://github.com/wfxr/forgit/issues/168#issue-1064088027
- Shell
- OS

use fish to interpret preview command

---

conf.d/forgit.plugin.fish

Fix for: ga preview not working with fish

---

conf.d/forgit.plugin.fish

Revert #169 to fix both #171 and #172 
@p00f just giving you a heads up!! Something was fishy (pun intended) with the way your change was interacting with ga and the latest version of fish! 
If you have another idea for a fix let me know and we can test it out together 😄

Reverted change b1c4c11959929228afd9a60210fd02c65f00ceda to fix fish ga

---

conf.d/forgit.plugin.fish

Making #189 work for fish
- Shell
- OS

Added rename support for fish with gd --staged

---

conf.d/forgit.plugin.fish

Fix for fish `gcp` after the recent change.
Working well on my machine now! @carlfriedrich would you review and make sure this seems reasonable? 
@wfxr would you try `gcp` with your config just for some QA and make sure it's running well :)

Fish didn't like the tac/tail switch. Also removed some print statements

---

conf.d/forgit.plugin.fish
forgit.plugin.zsh

This was a requested change from @cjappl as part of #219. Since we're not merging that PR, I'm submitting this separately, because I find it really useful for the code consistency.
There was also a tiny bug left for `git::cherry_pick`, where the SHA was not correctly parsed if `FORGIT_LOG_GRAPH_ENABLE` was set to false. I fixed this on the way, since it was the only command that parsed the SHA differently than the other commands.
I also included the `tr -d [:space:]` part in the variable, which is only used for copying the SHA to the clipboard but shouldn't cause trouble in the other use cases. @wfxr Can you check if copying still works correctly?
- Shell
- OS

Add variable "forgit_extract_sha"

---

conf.d/forgit.plugin.fish

Part two of the original #231 
It would be nice to add this functionality to bash/zsh @wfxr or @carlfriedrich if you have time :) 
Going to merge this basically straight away, as I see it being a huge gain to my personal workflow!

Add ability to checkout existing branch with gcb

---

conf.d/forgit.plugin.fish

Pretty simple one, only affects fish. Going to merge directly

Adding a wraps to get fish to autopopulate branches with tab complete

---

forgit.plugin.zsh

fixes https://github.com/wfxr/forgit/issues/256
fixes https://github.com/wfxr/forgit/issues/257
- Shell
- OS
Fixes:
* https://github.com/wfxr/forgit/issues/256
* https://github.com/wfxr/forgit/issues/257

fix: compatibility check not working in bash

---

README.md

See https://github.com/junegunn/fzf/issues/3256 for reference.
Fixes #298
- Shell
- OS

Fix wrong documentation concerning tab toggle direction

---

README.md

forgit is now being packaged by Homebrew. It was added in https://github.com/Homebrew/homebrew-core/pull/129392. This change adds installation instructions to the README.
- Shell
- OS

README: add `brew` instructions

---

.github/workflows/aur.yaml
README.md

Added a GitHub action that updates [aur/forgit](https://aur.archlinux.org/packages/forgit) when a new release is published. I've also mentioned the AUR packages in the README. This closes #311.
@wfxr could you please upload the required secrets for this:
`AUR_PRIVATE_KEY`: A private ssh key for the AUR
`AUR_USERNAME`: sandroid
`AUR_EMAIL` sandroid \<at\> posteo \<dot\> net
Once this is done I'll give this some testing and mark it as ready for review.
- Shell
- OS

AUR release action

---

bin/git-forgit

Fixes #333
This PR is based on #326. I will rebase and mark it as ready for review, once #326 is merged.
- Shell
- OS

Fix preview of deleted files with gsp

---

README.md

- [] I have commented my code in hard-to-understand areas
Fig was effectively sunset by Amazon from 1. September 2024
- Shell
- OS

Remove mention of Fig

---

README.md

Adding sheldon.cli configuration for zsh as an example.
- Shell
- OS

Update README.md with sheldon plugin manager configuration example

---

README.md

This is a follow-up of #424.
- Shell
- OS

Meta: Improve the documentation for overriding aliases

---

bin/git-forgit

Fix: use FORGIT_SHOW_FZF_OPTS in _forgit_show
